version: "3"
services:
  web:
    image: flask-advice-health:latest
    container_name: flask-advice-health
    restart: always
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:5000/health-check || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
#    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 wsgi:app
